# Site Info
title: <tt>=nil;</tt> Foundation Blog
tagline: ''
description: ''
baseurl: ''
url: https://blog.nil.foundation

# Site configurations
plugins:
  - jekyll-paginate
markdown: kramdown

# About/contact
author: Mikhail Komarov

bio: 
  
contact:
    #   - title: Linkedin
    # link:  https://www.linkedin.com/in/your_id

   - title: Github
     link:  https://github.com/nilfoundation

     #   - title: Instagram
     #     link:  https://www.instagram.com/your_id

   - title: Twitter
     link:  https://www.twitter.com/nil_foundation

     #   - title: Gmail
     #     link:  mailto:yourmail@abc.com
  
     #skills:
     #   - title: C
     #     level: 91
     #     color: primary
     #
     #   - title: C++
     #     level: 81
     #     color: success
     #     
     #   - title: Python
     #     level: 69
     #     color: warning
     #     
     #   - title: Html
     #     level: 95
     #     color: primary
     #     
     #   - title: CSS
     #     level: 89
     #     color: info     
     #
     #   - title: Jekyll
     #     level: 88
     #     color: danger
     #
# Navigation (2nd level links supported)

toc:
  - title: Home
    url: https://nil.foundation
  - title: Blog
    url: https://blog.nil.foundation
  - title: Projects
    url: https://nil.foundation/#projects
