# Site Info
title: "<span style='font-family:Menlo, Courier, monospace'>=nil;</span> Foundation Blog"
tagline: ''
description: ''
baseurl: ''
url: https://blog.nil.foundation

# Site configurations
plugins:
  - jekyll-paginate
markdown: kramdown

# About/contact
author: Mikhail Komarov

bio: 
  
contact:
   - title: Linkedin
     link:  https://www.linkedin.com/company/nil-foundation

   - title: Github
     link:  https://github.com/nilfoundation

     #   - title: Instagram
     #     link:  https://www.instagram.com/your_id

   - title: Twitter
     link:  https://twitter.com/nil_foundation

   - title: Email
     link:  mailto:nemo@nil.foundation
  
     #skills:
     #   - title: C
     #     level: 91
     #     color: primary
     #
     #   - title: C++
     #     level: 81
     #     color: success
     #     
     #   - title: Python
     #     level: 69
     #     color: warning
     #     
     #   - title: Html
     #     level: 95
     #     color: primary
     #     
     #   - title: CSS
     #     level: 89
     #     color: info     
     #
     #   - title: Jekyll
     #     level: 88
     #     color: danger
     #
# Navigation (2nd level links supported)

navbar:
  - title: Home
    url: https://nil.foundation
  - title: About
    url: https://nil.foundation/#about
  - title: Projects
    url: https://nil.foundation/#projects
  - title: Partners
    url: https://nil.foundation/#partners
  - title: Contact
    url: https://nil.foundation/#contact
